spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: oscargk707yzyz.
logging:
  level:
    root: info
    com.yz: debug
  file:
    path: log/blog-dev.log
